# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a GPL-3.0
# license that can be found in the LICENSE file.

---
# midgard common settings
title: "Changkun"
domain: localhost # domain that runs midgard server

# midgard server settings
# these settings are only used in server mode (run under `mg server`)
server:
  addr: 0.0.0.0:80
  mode: debug # or debug/release/test
  store: # data folder is in ./data
    prefix: /midgard # access via changkun.de/midgard/*
    backup:
      enable: true # enable backup
      interval: 60 # every hour
      repo: https://github.com/changkun/midgard-data.git
  auth:
    # the following two configures your midgard credentials
    user: changkun
    pass: aBWJnteJbt!j3G!qehLnJmbcgLqkkXuEusz9m4@JeqUqwZD*Dc

# midgard daemon settings
# these settings are only used in daemon mode (run under `mg daemon run`)
daemon:
  addr: localhost:9125
